name: Infinitude
version: "1.0.9"
slug: infinitude

description: Carrier Infinity thermostat proxy

url: https://github.com/nebulous/infinitude

startup: services
boot: auto

arch:
  - aarch64

host_network: true

ingress: true
ingress_port: 3000
ingress_entry: /

panel_icon: mdi:thermostat
panel_title: Infinitude

ports:
  3000/tcp: 3000

ports_description:
  3000/tcp: Carrier Infinity Proxy

options:
  app_secret: Pogotudinal
  pass_reqs: 1020
  mode: Production
  mqtt_broker: "core-mosquitto:1883"
  mqtt_user: "david"
  mqtt_pass: "meach1"
  mqtt_prefix: "homeassistant"
  mqtt_topic: "infinitude"

schema:
  app_secret: str
  pass_reqs: int
  mode: str
  mqtt_broker: str
  mqtt_user: str
  mqtt_pass: password
  mqtt_prefix: str
  mqtt_topic: str