name: Infinitude
version: "1.0.7"
slug: infinitude

description: Carrier Infinity thermostat proxy

url: https://github.com/davidtaillefer/infinitude

startup: services
boot: auto

arch:
  - aarch64

host_network: true

ports:
  3000/tcp: 3000

ports_description:
  3000/tcp: Carrier Infinity Proxy

webui: "http://[HOST]:[PORT:3000]/"

options:
  app_secret: Pogotudinal
  pass_reqs: 1020
  mode: Production
  mqtt_broker: "core-mosquitto:1883"
  mqtt_user: "david"
  mqtt_pass: "meach1"
  mqtt_prefix: "homeassistant"
  mqtt_topic: "infinitude"

schema:
  app_secret: str
  pass_reqs: int
  mode: str
  mqtt_broker: str
  mqtt_user: str
  mqtt_pass: password
  mqtt_prefix: str
  mqtt_topic: str
